services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digital-product-book:latest
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/http.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
